// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUtLDR16iG6Sh50RqjFGdNmn00zdV318',
    appId: '1:404403512807:web:5055aebbb309c79e7a4942',
    messagingSenderId: '404403512807',
    projectId: 'reelix-5be39',
    authDomain: 'reelix-5be39.firebaseapp.com',
    storageBucket: 'reelix-5be39.firebasestorage.app',
    measurementId: 'G-JLRWSRX6FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxReoRgSZp3nsrfzf1vR8nPH0LSxQjvYk',
    appId: '1:404403512807:android:2c00377d62dd1c3a7a4942',
    messagingSenderId: '404403512807',
    projectId: 'reelix-5be39',
    storageBucket: 'reelix-5be39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rNVec_gKHIRcenbnMLsJizATe0kYItw',
    appId: '1:404403512807:ios:704e390cf4c98e957a4942',
    messagingSenderId: '404403512807',
    projectId: 'reelix-5be39',
    storageBucket: 'reelix-5be39.firebasestorage.app',
    iosClientId: '404403512807-lm7395gqo1f7p2aqq07bikrthjn6fg3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8rNVec_gKHIRcenbnMLsJizATe0kYItw',
    appId: '1:404403512807:ios:704e390cf4c98e957a4942',
    messagingSenderId: '404403512807',
    projectId: 'reelix-5be39',
    storageBucket: 'reelix-5be39.firebasestorage.app',
    iosClientId: '404403512807-lm7395gqo1f7p2aqq07bikrthjn6fg3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKUtLDR16iG6Sh50RqjFGdNmn00zdV318',
    appId: '1:404403512807:web:4bc0c41374228e1f7a4942',
    messagingSenderId: '404403512807',
    projectId: 'reelix-5be39',
    authDomain: 'reelix-5be39.firebaseapp.com',
    storageBucket: 'reelix-5be39.firebasestorage.app',
    measurementId: 'G-16ETXXSW0H',
  );

}